class Commands:
    LEECH = "leech@privateurldownloaderbot2"
    PURGE = "purge@privateurldownloaderbot2"
    PAUSEALL = "pauseall@privateurldownloaderbot2"
    RESUMEALL = "resumeall@privateurldownloaderbot2"
    STATUS = "status@privateurldownloaderbot2"
    SETTINGS = "settings@privateurldownloaderbot2"
    EXEC = "exec@privateurldownloaderbot2"
    UPLOAD = "upload@privateurldownloaderbot2"
    YTDL = "ytdl@privateurldownloaderbot2"
    PYTDL = "pytdl@privateurldownloaderbot2"
    ABOUT = "about@privateurldownloaderbot2"
    GETLOGS = "getlogs@privateurldownloaderbot2"
    SERVER = "server@privateurldownloaderbot2"
    USERSETTINGS = "usetting@privateurldownloaderbot2"
    INSTADL = "instadl@privateurldownloaderbot2"
